### ISSUE TITLE
Compat Issue with First Person Model Mod

### ISSUE THREAD

**Issue by AzureMonument** [ewewukek/mc-musketmod#7] opened 2021-08-15 02:12 UTC
When using the musket with the first person model mod, after you reload it visibly seems to duplicate itself, with one musket being held properly according to the player model, and another floating as if in normal first-person perspective.
![2021-08-14_22 04 28](https://user-images.githubusercontent.com/43318292/129464754-b61d540b-cbf1-49f6-8a55-ca56ee093830.png)

Works 'normally' in the off hand (I'll be submitting a feature request for offhand capability shortly).
![2021-08-14_22 04 37](https://user-images.githubusercontent.com/43318292/129464750-fb1e7b79-ad81-4437-b72d-f9363a6d28ed.png)

**Comment by ewewukek** [comment] 2021-08-15 05:04
could not reproduce on forge-1.16.5 and fabric-1.17.1 (First Person Model doesn't have a forge 1.17 version yet). tested on latest version of FPS and it's dependencies.
this may be a compatibility issue with another mod, what are other mods you are using?

**Comment by ewewukek** [comment] 2021-08-15 20:02
confirmed in forge 1.16.5

**Comment by AzureMonument** [comment] 2021-08-16 17:00
Wildfire's gender mod and the animation mod that exists to go alongside first person model may be interfering. I'm also using tweakaroo- and a host of other mods- but those are the ones I can think of off the top of my head. Fabrication as well.

**Comment by ewewukek** [comment] 2021-08-30 11:33
fixed in latest release

**Closed by ewewukek** 2021-08-30 11:33 UTC
